### ISSUE TITLE
Review GitHub Repo Configuration

### ISSUE THREAD

**Issue by dev-brendanprice** [brendanprice2003/D2-Synergy#23]
The settings panel has functionality that has not been configured that is either necessary for an open-source community, or, can serve to be useful in the near future.

Review over the settings panel and setup "things" up.

**Comment by dev-brendanprice** [comment]
Contributing standards are to be formalized, asap.

**Comment by dev-brendanprice** [comment]
Contributing Standards have been completed for all that is able to be contributed towards within the project (in its current state).

**Comment by brendanprice2003** [comment]
Re-opening so I can review the possibility of being used:

- Snyk
- Webpack
- GitHub automatic versioning

**Comment by dev-brendanprice** [comment]
Re-opening so I can review the possibility of these items being used:

- Snyk
- Webpack
- GitHub automatic versioning

**Comment by dev-brendanprice** [comment]
Snyk is being used as an external source of verification.

Awaiting an integration for Snyk or some other similar service.

**Comment by dev-brendanprice** [comment]
Webpack will be used for the production version.

Github automatic version is not needed anymore.

**Comment by dev-brendanprice** [comment]
This is a stale issue as a new one has taken its place.

https://github.com/brendanprice2003/D2-Synergy/issues/63

**Comment by dev-brendanprice** [comment]
> Snyk is being used as an external source of verification.
> 
> Awaiting an integration for Snyk or some other similar service.

Snyk is not currently being used and will not be used until further planning and execution has taken place
