### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by dev-brendanprice** [brendanprice2003/D2-Synergy#3]
Implement practical error catching and handling with integrated error endpoints.

**Comment by brendanprice2003** [comment]
I have implemented a jQuery script that can browse defined variables, inside of chrome devTools.

**Comment by brendanprice2003** [comment]
Defined variables are things such as player structures, info and inventory items. Stuff like the definitions and random variables will not be shown as per "good" coding standards.

**Comment by dev-brendanprice** [comment]
Awaiting until user testing has commenced.
